services:
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    container_name: myapp
    volumes:
      - ..:/home/developer/workspace
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    command: uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: mydb
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  pg_data:
