services:
  app:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    container_name: app
    volumes:
      - ..:/home/developer/workspace
    ports:
      - "${APP_PORT}:8000"
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ".devcontainer/entrypoint.sh"

  db:
    image: postgres:15
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pg_data:
